############################################
### Protected routes for administrators. ###
############################################

### Delete one product.
DELETE http://localhost:8080/products/65eb9525ac19a50087e8769f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGVtYWlsLmNvbSIsImV4cCI6MTcwOTk2MTY1M30.ZPMZAom8errRLCm2nAlwFBqfRtLgCjYkrTqjOTUw9sk

############################################
### Protected routes for regular users. ###
############################################


############################################
###            Public routes.           ###
############################################

### Get all products.
GET http://localhost:8080/products
Content-Type: application/json