############################################
### Protected routes for administrators. ###
############################################


############################################
### Protected routes for regular users. ###
############################################


############################################
###            Public routes.           ###
############################################

### Get all products.
GET http://localhost:8080/products
Content-Type: application/json