############################################
### Protected routes for administrators. ###
############################################

### Get All Users.
GET http://localhost:8080/users
Content-Type: application/json
Authorization:

### Change a user "admin" field to true.
PATCH  http://localhost:8080/users/makeAdmin
Content-Type: application/json
Authorization:

{
    "email": "test1@email.com"
}


############################################
### Protected routes for regular users. ###
############################################

### Change a user "validated" field to true.
PATCH  http://localhost:8080/users/validate
Content-Type: application/json

{
    "email": "test2@email.com"
}

### Change the user information
PATCH  http://localhost:8080/users/updateInfo
Content-Type: application/json
Authorization:

{
    "password": "test4444"
}