### Get All Users (protected route that requires a valid JWT token and the user to be an admin).
GET http://localhost:8080/users
Content-Type: application/json
Authorization:

### Change a user "validated" field to true.
PATCH  http://localhost:8080/users/validate
Content-Type: application/json

{
    "email": "test2@email.com"
}

### Change a user "admin" field to true (protected route that requires a valid JWT token and the user to be an admin).
PATCH  http://localhost:8080/users/makeAdmin
Content-Type: application/json
Authorization:

{
    "email": "test1@email.com"
}